#!/usr/bin/env python3
"""Regenerate docs/commands.md and docs/models.md from the parser registry (run after adding parsers)."""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from clijson import supported_commands  # noqa: E402
from clijson.models import SCHEMAS  # noqa: E402
from clijson.platforms import list_platforms  # noqa: E402

FIXTURES = ROOT / "tests" / "fixtures"


def main() -> int:
    rows = supported_commands()
    by_platform = defaultdict(list)
    for r in rows:
        by_platform[r["platform"]].append(r)
    fixture_counts = defaultdict(int)
    for js in FIXTURES.rglob("*.json"):
        fixture_counts[js.parent.parent.name] += 1

    parsers = {r["parser"] for r in rows}
    lines = [
        "# Supported commands",
        "",
        "<!-- generated by scripts/gen_docs.py - do not edit by hand -->",
        "",
        f"**{len(parsers)} dedicated parsers** covering **{len(rows)} command patterns**. "
        "Anything not listed still parses through the generic engine (and through ntc-templates / Genie when installed).",
        "",
        "Grammar: `[optional]`, `(a | b)` alternatives, `<param>` single token, `<param...>` rest of line. "
        "Abbreviations are accepted everywhere (`sh ip int br`).",
        "",
        "| Platform | Parsers | Patterns | Regression fixtures |",
        "|---|---:|---:|---:|",
    ]
    for p in list_platforms():
        rs = by_platform.get(p.name, [])
        lines.append(f"| {p.display_name} (`{p.name}`) | {len({r['parser'] for r in rs})} | {len(rs)} | {fixture_counts.get(p.name, 0)} |")
    lines.append("")
    for p in list_platforms():
        lines += [f"## {p.display_name} (`{p.name}`)", "", "| Command | Normalized model | Parser | Description |", "|---|---|---|---|"]
        for r in sorted(by_platform.get(p.name, []), key=lambda r: r["command"]):
            cmd = r["command"].replace("|", "\\|")
            lines.append(f"| `{cmd}` | {('`' + r['intent'] + '`') if r['intent'] else ''} | `{r['parser']}` | {r['description']} |")
        lines.append("")
    out = ROOT / "docs" / "commands.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}: {len(parsers)} parsers, {len(rows)} patterns")
    write_models(rows)
    return 0


def write_models(rows) -> None:
    producers = defaultdict(list)
    for r in rows:
        if r["intent"]:
            short = r["command"].split(" [")[0].split(" (")[0]
            item = f"{r['platform']}: `{short}`"
            if item not in producers[r["intent"]]:
                producers[r["intent"]].append(item)
    lines = [
        "# Normalized models",
        "",
        "<!-- generated by scripts/gen_docs.py - do not edit by hand -->",
        "",
        "`clijson.parse(..., normalize=True)` fills in `result.normalized` for commands that map to one of the",
        "models below. Each record has **exactly** these keys, in this order, on every vendor. A value is `None`",
        "when the device doesn't report it.",
        "",
        "Values are standardised:",
        "",
        "* statuses become `up` / `down` / `admin-down`",
        "* MAC addresses become `aa:bb:cc:dd:ee:ff`",
        "* uptimes are given as text and also in seconds where the schema has `*_seconds`",
        "* the protocol in `routes` is always lower case (`bgp`, `ospf`, `isis`, `static`, `connected`, `local`, …)",
        "* `vrf` is `default` for the global table",
        "",
    ]
    for intent, fields in SCHEMAS.items():
        lines += [f"## `{intent}`", "", "Fields: " + ", ".join(f"`{f}`" for f in fields), "", "Produced by:", ""]
        lines += [f"* {p}" for p in producers.get(intent, [])] + [""]
    out = ROOT / "docs" / "models.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}: {len(SCHEMAS)} models")


if __name__ == "__main__":
    sys.exit(main())
